# Generated by Django 3.0.3 on 2020-09-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('author_email', models.CharField(max_length=200)),
                ('parameter_file1', models.FileField(blank=True, default='', upload_to='uploads/')),
                ('parameter_file2', models.FileField(blank=True, default='', upload_to='uploads/')),
                ('parameter_file3', models.FileField(blank=True, default='', upload_to='uploads/')),
                ('parameter_file4', models.FileField(blank=True, default='', upload_to='uploads/')),
                ('screenshot', models.ImageField(upload_to='uploads/')),
                ('paper', models.CharField(blank=True, default='', max_length=500)),
                ('content_tag', models.CharField(blank=True, default='', max_length=100)),
                ('modality_tag', models.CharField(blank=True, default='', max_length=100)),
                ('dimension_tag', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
