# Generated by Django 3.0.3 on 2020-09-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelzoo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='title',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
