# Generated by Django 3.0.3 on 2020-09-15 14:26

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelzoo', '0002_model_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='markdown_file',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
    ]
