# Generated by Django 3.0.3 on 2020-09-16 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelzoo', '0003_model_markdown_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='model',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='model',
            name='markdown_file',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='model',
            name='screenshot',
            field=models.ImageField(blank=True, default='', upload_to='uploads/'),
        ),
    ]
