# Generated by Django 3.0.3 on 2020-09-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelzoo', '0005_auto_20200916_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='content_tag',
            field=models.CharField(choices=[('CT', 'CT'), ('MR', 'MR'), ('Ultrasound', 'Ultrasound'), ('MRI', 'MRI')], max_length=15),
        ),
    ]
