# Generated by Django 3.0.3 on 2020-09-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelzoo', '0006_auto_20200916_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='content_tag',
        ),
        migrations.RemoveField(
            model_name='model',
            name='dimension_tag',
        ),
        migrations.RemoveField(
            model_name='model',
            name='modality_tag',
        ),
        migrations.AddField(
            model_name='model',
            name='content',
            field=models.CharField(blank=True, choices=[('CT', 'CT'), ('MR', 'MR'), ('Ultrasound', 'Ultrasound'), ('MRI', 'MRI')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='model',
            name='dimensions',
            field=models.CharField(blank=True, choices=[('2D', '2D'), ('3D', '3D'), ('4D', '4D')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='model',
            name='modality',
            field=models.CharField(blank=True, choices=[('Lung', 'Lung'), ('Brain', 'Brain'), ('Prostate', 'Prostate')], default='', max_length=15),
        ),
    ]
