# Generated by Django 3.0.3 on 2020-09-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelzoo', '0007_auto_20200916_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
