# Generated by Django 3.0.3 on 2020-09-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelzoo', '0008_model_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='checked',
            new_name='reviewed',
        ),
    ]
