# Generated by Django 3.0.3 on 2020-09-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelzoo', '0012_auto_20200916_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='checked',
        ),
        migrations.AddField(
            model_name='model',
            name='short_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
