# Generated by Django 3.0.3 on 2020-09-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelzoo', '0014_model_reviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='markdown_file',
            new_name='ipynb',
        ),
        migrations.AddField(
            model_name='model',
            name='readme',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='model',
            name='content',
            field=models.CharField(blank=True, choices=[('Lung', 'Lung'), ('Brain', 'Brain'), ('Prostate', 'Prostate')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='model',
            name='modality',
            field=models.CharField(blank=True, choices=[('CT', 'CT'), ('MR', 'MR'), ('Ultrasound', 'Ultrasound'), ('MRI', 'MRI')], default='', max_length=15),
        ),
    ]
