# Generated by Django 3.0.3 on 2020-09-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelzoo', '0015_auto_20200918_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='readme_txt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='model',
            name='modality',
            field=models.CharField(blank=True, choices=[('CT', 'CT'), ('Ultrasound', 'Ultrasound'), ('MRI', 'MRI')], default='', max_length=15),
        ),
    ]
