# Generated by Django 3.0.3 on 2020-09-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelzoo', '0016_auto_20200918_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='author_email',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='model',
            name='author_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
