# Generated by Django 3.0.3 on 2020-09-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelzoo', '0017_auto_20200918_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='parameter_file10',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file5',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file6',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file7',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file8',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file9',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
    ]
