# Generated by Django 3.0.3 on 2020-10-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelzoo', '0019_auto_20201006_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='parameter_file10',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file11',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file12',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file13',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file14',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file15',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file16',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file17',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file18',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file19',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file20',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file21',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file22',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file23',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file24',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file25',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file26',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file27',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file28',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file29',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
    ]
