# Generated by Django 3.0.3 on 2020-10-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelzoo', '0020_auto_20201006_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='parameter_file30',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file31',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file32',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file33',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='model',
            name='parameter_file34',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='model',
            name='content',
            field=models.CharField(blank=True, choices=[('Lung', 'Lung'), ('Brain', 'Brain'), ('Prostate', 'Prostate'), ('Chest', 'Chest'), ('Cervix', 'Cervix')], default='', max_length=15),
        ),
    ]
