# Generated by Django 3.0.3 on 2020-10-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelzoo', '0021_auto_20201012_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='github',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
