# Generated by Django 3.0.3 on 2020-10-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelzoo', '0022_model_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='con_mod_dims',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
