# Generated by Django 3.0.3 on 2020-10-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelzoo', '0023_model_con_mod_dims'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='author_email',
        ),
        migrations.RemoveField(
            model_name='model',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='model',
            name='description',
        ),
        migrations.RemoveField(
            model_name='model',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='model',
            name='readme_txt',
        ),
        migrations.RemoveField(
            model_name='model',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='model',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='model',
            name='modality',
            field=models.CharField(blank=True, choices=[('CT', 'CT'), ('Ultrasound', 'Ultrasound'), ('MRI', 'MRI'), ('PET', 'PET'), ('X-Ray', 'X-Ray')], default='', max_length=15),
        ),
    ]
