# Generated by Django 3.0.3 on 2020-10-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelzoo', '0025_auto_20201015_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
