# Generated by Django 3.0.3 on 2020-10-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelzoo', '0027_auto_20201020_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='model',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='model',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='model',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='model',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='model',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='model',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='model',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='model',
            name='image9',
        ),
    ]
