# Generated by Django 3.1.2 on 2020-10-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelzoo', '0030_auto_20201021_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='content',
            field=models.CharField(blank=True, choices=[('Head & Neck', 'Head & Neck'), ('Brain', 'Brain'), ('Carotid', 'Carotid'), ('Chest/Lung', 'Chest/Lung'), ('Cardiac', 'Cardiac'), ('Abdomen', 'Abdomen'), ('Liver', 'Liver'), ('Cervix', 'Cervix'), ('Prostate', 'Prostate'), ('Pelvis', 'Pelvis'), ('Knee', 'Knee'), ('Head', 'Head & Neck'), ('Neck', 'Head & Neck'), ('Chest', 'Chest/Lung'), ('Lung', 'Chest/Lung'), ('Cervical', 'Cervix'), ('Pelvic', 'Pelvis')], default='', max_length=15),
        ),
    ]
